---
kind: "operation"
client: "rug-cli 0.21.4"
executor:
  name: "EnableTravisForRugArchive"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.12.0"
  origin:
    repo: "git@github.com:atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "678d3e9"
  parameters:
    - "owner": "atomist"
    - "repo": "handlers"
    - "org": ".org"
    - "github_token": "3**************************************9"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t***************y"
    - "maven_token": "z**************7"

---
kind: "operation"
client: "rug-cli 0.21.4"
generator:
  name: "NewHandlersProject"
  group: "atomist"
  artifact: "handlers"
  version: "0.6.0"
  origin:
    repo: "https://github.com/atomist/handlers.git"
    branch: "23285115100d4a061a004f01e273e87d4bc58795"
    sha: "2328511*"
  parameters:
    - "project_name": "handlers"
    - "group_id": "atomist-rugs"
    - "version": "0.1.0"

---
kind: "operation"
client: "rug-cli 0.21.4"
executor:
  name: "EnableTravisForRugArchive"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.12.0"
  origin:
    repo: "git@github.com:atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "678d3e9"
  parameters:
    - "owner": "atomist-rugs"
    - "repo": "default-handlers"
    - "org": ".org"
    - "github_token": "3**************************************9"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t***************y"
    - "maven_token": "z**************7"

---
kind: "operation"
client: "rug-cli 0.21.4"
executor:
  name: "EnableTravisForRugArchive"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.12.0"
  origin:
    repo: "git@github.com:atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "678d3e9"
  parameters:
    - "owner": "atomist-rugs"
    - "repo": "default-handlers"
    - "org": ".org"
    - "github_token": "3**************************************9"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t***************y"
    - "maven_token": "z**************7"

---
kind: "operation"
client: "rug-cli 0.32.0"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.5"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "caa346c"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.33.4"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-editors"
  version: "0.27.1"
  origin:
    repo: "https://github.com/atomist/rug-editors.git"
    branch: "3de333b4aefd678ae14f196ab155647241de3746"
    sha: "3de333b"

---
kind: "operation"
client: "rug-cli 1.0.0-m.1"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.29.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "0f425945c62957ccc2ccb63e9980e6f78b97a4a1"
    sha: "0f42594"

---
kind: "operation"
client: "rug-cli 1.0.0-m.2"
editor:
  name: "AddLicenseHeaders"
  group: "atomist"
  artifact: "license-rugs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:atomist/github-rugs.git"
    branch: "render-issues"
    sha: "7ca2527"
  parameters:
    - "rootDir": "*[@name=".atomist"]/handlers"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.4"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.1"
  origin:
    repo: "git@github.com:atomist/github-rugs.git"
    branch: "master"
    sha: "b383f71*"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.4"
editor:
  name: "UpdateRug"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.31.1"
  origin:
    repo: "git@github.com:atomist/github-rugs.git"
    branch: "master"
    sha: "b383f71*"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-m.5"
editor:
  name: "UpdateSupportFiles"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.32.1"
  origin:
    repo: "git@github.com:atomist/github-rugs.git"
    branch: "master"
    sha: "4e0cea9*"

