dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: KxNnXbbZ5S/4nmPuVk3hEMBxq5Qfn4hWjxxLozWsoRsvRcUfdTp7kODUpLyNXQVTZtPMWiBML64DtIjYEn1XzUn6q7pu5SyqJBOR+FRdtrsJ+6l5QisRz5lmX9klh3U4TpU3nGVROzG31lxsVNsmH9v/x2aep5d9YbAYBQge08pwpWNUuls2dSQRiVxv6PZXSEY5D0KieyJvz8ZAnHzSB3klTbAuVk3DE5/hA67b2fmH8JOUNPUl9OjLV/1iRlIALeHSmjMj2LSK6UWp08895JgqD30VxafZ0tDFyL6Q/xLUPc3VZFYQPNZOaYEpLMXd+kpb9Yf7NtzMNBrNKBX3eZ4Tvg21h57m+/QW/XsMqvi+U7P+UpjkdW0zUxG6ZO0byl6FPCaxYjTcOlMGFYJL09TUEX9YyN+bfMpWqevV5DPdccNxokD8AfbffYbi2ycSDeE5KLajZThz1J3wwyqVj/SSZ/21VzXcYjdh44r/mnFi0L+1MEEMF40pb+u5CQYF/6gjzfg8OlZ+rU71dTLIxOw23uW6Uf9rT/VkDRTceRDd8aSbOdGprAArEqnyspSkHfbSoRvA1VAcfGvyv8ADYAIxQaN8VNc+QmO/rl2bcqgHjY44/+reF+97XC+yKCI/6wgZic70KleWO00I0iKNlehxBLfIlv2EuHGCJyQNhdc=
  - secure: rNKqQMIjuXTpuT3FKeBv580jKeUGJDLTkDxUb7dUhjuaE09svizPJF4f1CGTwfHF1QKWbsnW8iJpNdD8hWJNJEl324JznA7Sb35PNGtjtnzhRcIkgj34d+MxpCTilY2Hwz9x5BBdPvOlmVsx5eFhPlPiFCedt72IAtM3rOXJ94nIAz6ZFZh60L61XfuH+3Zz6sRO1finO0gOY82HfXrvXE7NMBKpSiZ6d0nokLjEWId/eIPbW0iQTH18k49PHHpWUF1D5snkJ8LMcpVMieMqFPc5ewny26KTDrG95hYt+j88jBh6wGJFweCDhOwGJM6EGVTGm5bUI2RWYQ5GA9/gypmKfLx8LR2zsxLiSXbsxUSw0Cf3XeVf5+1fqO5ycf/EfR5MHf1T2AdWywmiL+b9t23UXcNmgFCL9HSW8e6czcQG8ekjntERNZsMwVbZf9Nlq2n0lHsXm4hfdJtJNzS0HnA9fTdULV8jm4nRS4aClJBQ9KIXDK3D/jfGwm4TDgzB4H0a/+hYqA9siR2eqEeOYOjqM9KLsA0ZhkmcYjDSp6SusfTqwSrmLl6cbGbYVITKQJKRzfkXrjntdWFqvwtZZ4RhPGg7NU2Vwz6gcXlcF4BcJOHudj7fLX39HNqaenyLn5JmUlO028NFgQOs0cTAJUuaeJJH13dpSNWY3sMiqGQ=
  - secure: G2b2sSkf1z+VID9tQwME/NqFdLTAxVTjagUkULxVEYRBYNTi6Dtv4YL60rqxjyzuXGRiNGrNsEPOLx5LHM/FV0psg1sFXwgQM7wZRTzy9VyrBMMsmhsAGY/I35mDBX+aX3F/PupxM5i76CYpHpQD2pIkR+r+q/YPO1RihjU9Hxfc4P2j2axnGwvfq1zGtz3AIB5bWtj58L9wYOnfYKxzyVCa6M2S+hzlUj2YMIhfJCR/mCzwGdZkVx7lT9qQPpnnGCU2UuAArKHgMMvNiX8kgeDtBMz6jv4w4WSKSJfRkdzR3PAHJz5ec0HZUsYsb5hInwLrjszYxBeRGfJl8yxHBC6PwGEQPUZYpKEexE+GFFONvv8ZxlVDbmiefY7p/vcVNEfhgDkTNHbPgHU6b6TOrpOfX9dRx/mfaPhtp9NgOgA9o2fOTuxllZ1fp3YJnAJm8AwLreot5PeOxA4EiDvAhvXPVXXio91/bB+vfwb4rWIBFMbqK0MziJGI3xOchyiGFnYrX3LGsYhoX7zxQo7eFuhl9aaBelmiB1fK5cz5vzi4JFyRgLVfVYSkR7qRHmziUaMvjDIhAgcFlhdu4FIHs2pbuZlbK56hIW4GfIOMD+obzvWeyCo99/cE+aiRReCX9FGjVA4NbS1CIYU/evZ5CJG9VJ7A1J2bnju5P3pdcQU=
install: nvm install 8.3.0
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - "$HOME/.atomist"
  - "$HOME/.npm"
deploy:
  provider: releases
  api_key:
    secure: b3N7GqDOVvw7JfFbR6Kuv5u8Dd7Z3RMTAFMC+Wl91FfQtS2rc4lEvpMPv5SlhVl9mKIfTfzUJl6me/KxBMQvhTh87Y3LqLrGcSGXMRNvfp4Wi9tT8z13vgunk5FbbvXtm4Se7JUM8hKv61i6uvJwDWdk+RfMRiI3VEWOxCmbq13S2WJfVKRK65oXJlBHPjkCXVrh9qKcJBf/OKThhPk3HrY9LwZhZt4FDi8pm8DKfPRGoGMFbrmOGhZMJmM7oKShhaMk70nOvgy4pbRdcbXM9Our+t3D7QFSyiacfruBgTBXrmiDLTnEuw5p21Ea4pyPtqsT3ymqtv6Oi83U4RMn5JGXplof3q5v7fNZ76f2S26xUJXXcMqt5ykai2LTWLwjqub19XdrqqNdQxHuJnUdopW+E/Q0AewUV3ahcQXDS1ZKHMtivchAs2MppcWBI8UdagqRJr+SzfD/GfMogAQe1Zq0N4E4SF0ywkVrmuaohKZ/IswSJMwMYHPqWlrWnW82LEHW9ZocRZyp39CJQfOVlE/K7BXk1bNbSAUchKda3+8Sh61egx+6Dw1zlnscFBCRWV0SvWh9fbdunt5b5kOIQex3iYj40wQDX5PXCBYUXw1HZOaRPxDCPPABG2cn+f7/CvJuS55GHp+/+y/xjCaGghxQgtDzFMKs91jFFdT8B1Q=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
