dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: Clo/X4MQa4+VkWTGIj8zRVFCzLPTXchbyCraW78+QKDGbSqm0tDFtp3rxEMPw83pNMeysZ8wCqc4aEDCeJK4yedtWAMwa90d2EuqXIhKve54YeUZvSm6pzzPb720ADIKvMRKOzS0wG9mA4wTw8x1jDdtndQYi+3oQjzBWJjHLT/ja+F9y1Y3ZCGs6lwunMeCFsOixAVpWc3f6CtfQZFi3Cm2G2c9uNHMy1UnZF9v22wDRy4IA6JM1wXOdtREkHi0rH4+ADcRMTygY9QmMotSNcnPXvBBMJNUlP87m7ocZYygmrsvgLg5XQQjuJbpkKHoGeXLxvCs72cvwwfyE+f8xhVslxdyA0SXozY5KoBMtE1USEgXOK3PhaGU8j7/yWyNhl2DE9N0mIjjuum7JjvCynmLnAxhzwjUFGfKVrQcPEpXiVCdnwv2THZCOknYigPCdtzVqMm5AgARCB8YiAP5gm7JMmdSM1a2F3mR+wrSzpxbFWHQ6mRQlnpvjt2lp0gTd0H1hEVX/6whTTAW5CeuJqUsXKV5yF8wS6SarMmnmUImBmhJcAycjE5wrq3AwuBc0gU1fiuCSYV+fHhDv0MjgrzkahjPY/9QkRCmbNiOUMHHd9yxxPWN0cpfG6Vncxk+hokJA3NPtWNGFex7AHq35X4LhsFxnQK74gf/9tO6zH0=
  - secure: TcH8PRaml3FVyggm/fXZkbv0o3CjlceWVVdgLww8cOKBsibVpUAHno3It10OMol0xF0cXUKIJtZYb4+vtIqLekrvskwipa5f7eM0ZQkMzMf8smu2S51jmylm8yi8VDIeCuPccD+4USxdYexGXAd9YjasbS4AXEyDdNTHD8tnB/zG0vPG+5ABXwnTILPUm+UvGQNVV/o1p+U1xoP8Jl6nzMTIjnFnGmL63Lt/DF5nKW4lcCLH8K0ypIV+AeTZYwepZW+Z74vrngxCALCeI94o+OLX+ZdfkeZSmIDQaQtRshfHg4QTwnABN1csNHHFSoZDJFZcfDf+thpkd8SUtlphuJTzUkskpEoX97tHrs9cnzrjk0OFkFlCOyCJSdxcdBCCtTwmwPFeRcX65Hcnff2mzSZBGtKx78ewEs0leUvbuwcw0An8Yrt8sflwk+Of2Lc6HnvxzPOT8ujqclMYkESGbk5QYBLxjf3bsM22MZgvtGX7wHTFN2vcCc0Xjokt7O+E24ymVIjm2IPwuPtUAUY+RdatKRfmW6sMNQl1ZkdstWIbTdsqif7M6lk7ONpe8CbFGikdCqyzmCg8FpZsB0dIW2z4/2HXKNSDNfWU4f0Jdk+F3F5NvcglVm0ZHOTFoWh2k+8XUhjoZqE2hmQIztud0cxtaBXDFszXud8Zs+dhvBo=
  - secure: WQm4FHCPEcXjXQx2ACmYEN0VVccdHgJVnppHM75zZgaQC0MdACGoGYABZuDGpBtq0MgrfpQAZ8oKNC505PUd6U8RJOLgI5g/XlpOe55+XA+E0LzhEKHkwYu8jz9xTdmJIeNz8cgAe2fxmRTHfWoKdH+EWvYUgo5r3zwiKX5rvxuWEbGgl1Yojz3amatqYnOc2cgfxHF2ldYUiqeEcO4anwgwPDdB3f3JdDl1Ki01OfL/Fjlau07LRK7pC1EOeatna+kt1GcQWOaifgiFxbeO3raPT4zsF/3fE0esilqqkN8rMp5sTCeL6/PLUYhj7IaYeQ+THz+GhkwsZ8vY1PKP5G/EVWhH/ZQhOJGtI+uLd1CeGE5dd51LWW6Aw/mYQ4FMwlJAMNIlMx2ZAvAiTrMLIhyKLPLgVXbZfxbIeGUYQVIGAZQ1oqs1w/fwfw5VmPUKqs+4LU4OFYScdeik570pT2iOvdjsux8G99vkLIbv7E9OVQMGWwskWMSGe6Da2FbKPuQH4iJBdn4rMT35ERFxm9HPuyOWsQc39PSX95Yz7mBCX9C9JfswQ3mYcKucANQPdEloKHZYIbEFPvJciI6boUJBoHjUxrrg5FqfpiSLkE1fPivQtGwd0+xgObpkOl95NQqjUP4XaQlJacTE/1GqRBgsSbbKTgjErAkHjybfY6c=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
