dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: wRS5SvsP9E/kH24aYoycAdIoLpNpfcHIaSgRcYP8l905dIRpna2BTgfpxuxr+ZUFyNnjNy0IzXb/7nOtFQk01Rzv3dubQUsehLQ9s1dMEp+p9aWCFZciRN/mXXAmyXj0i2VB/tvGguF1Jb68b76i5iP3QyKzh6RZgtEZz0H1W+lb2tC5imkjJPq7184wL556hRD1L+Mnt/SYC48IbyzEQreA/DoewV7vSUEnQqJfPg4+4mqrpK6hEXjUc1CJqK0iKIp1NjcPRqq61iawTLgCRCwuy4WTTMXD00h8FktPLHtuLXQlU6Tt1bNlqVxtx1Lk9gSAHlwuriEJZRufxyGkEz6oggzGtBLkmccA/p3/0OA8xvXenuuj6qCRif3PNRveX0khlV0GUHvOi6aPBZ90OhDwRoYJvIS/0fhfP5KzfHJ8TiNVjNZp3Yjk1kAVxpoBaToO8gMtk6VDKTO8PUs42oDQds6wGQBoflZ9sCC71KPPhO967G1jn7THfscGwQr6tJDjP6UD4FECTQ0jRsvj2u/VvKufLca5wcTsvOnmcKJihlRHfxLxXVH2bU5h559Z8VGdbtrteO5ZyPZEi6xWSMgcpfJjC4u3jJlGcHkZpdMkq4Nr1oIW8qiMNXYzSEB1zKqnE0TSXxqzzKIDhXrWO2ALdDSZglcb/P6C4xW69XQ=
  - secure: KxNnXbbZ5S/4nmPuVk3hEMBxq5Qfn4hWjxxLozWsoRsvRcUfdTp7kODUpLyNXQVTZtPMWiBML64DtIjYEn1XzUn6q7pu5SyqJBOR+FRdtrsJ+6l5QisRz5lmX9klh3U4TpU3nGVROzG31lxsVNsmH9v/x2aep5d9YbAYBQge08pwpWNUuls2dSQRiVxv6PZXSEY5D0KieyJvz8ZAnHzSB3klTbAuVk3DE5/hA67b2fmH8JOUNPUl9OjLV/1iRlIALeHSmjMj2LSK6UWp08895JgqD30VxafZ0tDFyL6Q/xLUPc3VZFYQPNZOaYEpLMXd+kpb9Yf7NtzMNBrNKBX3eZ4Tvg21h57m+/QW/XsMqvi+U7P+UpjkdW0zUxG6ZO0byl6FPCaxYjTcOlMGFYJL09TUEX9YyN+bfMpWqevV5DPdccNxokD8AfbffYbi2ycSDeE5KLajZThz1J3wwyqVj/SSZ/21VzXcYjdh44r/mnFi0L+1MEEMF40pb+u5CQYF/6gjzfg8OlZ+rU71dTLIxOw23uW6Uf9rT/VkDRTceRDd8aSbOdGprAArEqnyspSkHfbSoRvA1VAcfGvyv8ADYAIxQaN8VNc+QmO/rl2bcqgHjY44/+reF+97XC+yKCI/6wgZic70KleWO00I0iKNlehxBLfIlv2EuHGCJyQNhdc=
  - secure: rNKqQMIjuXTpuT3FKeBv580jKeUGJDLTkDxUb7dUhjuaE09svizPJF4f1CGTwfHF1QKWbsnW8iJpNdD8hWJNJEl324JznA7Sb35PNGtjtnzhRcIkgj34d+MxpCTilY2Hwz9x5BBdPvOlmVsx5eFhPlPiFCedt72IAtM3rOXJ94nIAz6ZFZh60L61XfuH+3Zz6sRO1finO0gOY82HfXrvXE7NMBKpSiZ6d0nokLjEWId/eIPbW0iQTH18k49PHHpWUF1D5snkJ8LMcpVMieMqFPc5ewny26KTDrG95hYt+j88jBh6wGJFweCDhOwGJM6EGVTGm5bUI2RWYQ5GA9/gypmKfLx8LR2zsxLiSXbsxUSw0Cf3XeVf5+1fqO5ycf/EfR5MHf1T2AdWywmiL+b9t23UXcNmgFCL9HSW8e6czcQG8ekjntERNZsMwVbZf9Nlq2n0lHsXm4hfdJtJNzS0HnA9fTdULV8jm4nRS4aClJBQ9KIXDK3D/jfGwm4TDgzB4H0a/+hYqA9siR2eqEeOYOjqM9KLsA0ZhkmcYjDSp6SusfTqwSrmLl6cbGbYVITKQJKRzfkXrjntdWFqvwtZZ4RhPGg7NU2Vwz6gcXlcF4BcJOHudj7fLX39HNqaenyLn5JmUlO028NFgQOs0cTAJUuaeJJH13dpSNWY3sMiqGQ=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
